version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e
      POSTGRES_DB: online-shop
    ports:
      - "5432:5432"
    networks:
      - shop_network
networks:
  shop_network:
    driver: bridge
